In [7]:
import random
import plotly.graph_objects as go
import numpy as np
import pandas as pd
import dash_html_components as html
import dash_core_components as dcc
import dash
import plotly.graph_objects as go
import dash
from jupyter_dash import JupyterDash
from dash.dependencies import Output, Input
import dash_core_components as dcc
import dash_html_components as html
import plotly
import random


# Read data from a csv
z_data = pd.read_csv(
    'https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv')


import numpy as np 
mu, sigma = 0, 50 
# creating a noise with the same dimension as the dataset (2,2) 
noise = np.random.normal(mu, sigma, z_data.shape)
s1 = go.Surface(z=((z_data+noise)/(z_data+noise).max().max()).values)
noise = np.random.normal(mu, sigma, z_data.shape)
s2 = go.Surface(z=((z_data+noise)/(z_data+noise).max().max()).values)
noise = np.random.normal(mu, sigma, z_data.shape)
s3 = go.Surface(z=((z_data+noise)/(z_data+noise).max().max()).values)
noise = np.random.normal(mu, sigma, z_data.shape)
s4 = go.Surface(z=((z_data+noise)/(z_data+noise).max().max()).values)
noise = np.random.normal(mu, sigma, z_data.shape)
s5 = go.Surface(z=((z_data+noise)/(z_data+noise).max().max()).values)

frames = [{"data":[s1]},{"data":[s2]},{"data":[s3]},{"data":[s4]},{"data":[s5]}]

fig = go.Figure(data=[s1],layout=go.Layout(
        xaxis=dict(range=[0, 16], autorange=False),
        yaxis=dict(range=[0, 13], autorange=False),
        hovermode="closest",
        title="Start Title"
    ))


app = JupyterDash(__name__)
app.layout = html.Div(
    [
        dcc.Graph(id='live-graph'),
        dcc.Interval(
            id='graph-update',
            interval=1000,
            n_intervals=0
        ),
    ]
)

@app.callback(Output('live-graph', 'figure'),
              [Input('graph-update', 'n_intervals')])
def update_graph_scatter(input_data):
    if input_data is None:
        return dash.no_update

    return frames[input_data % 5]

app.run_server(port=8050)

Dash app running on http://127.0.0.1:8050/

:

In [4]:
z_data.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
0,0,27.809850,49.61936,83.080670,116.66320,130.41400,150.72060,220.1871,156.1536,148.6416,...,49.96142,21.89279,17.02552,11.743170,14.752260,13.667100,5.677561,3.312340,1.156517,-0.147662
1,1,27.719660,48.55022,65.213740,95.27666,116.99640,133.90560,152.3412,151.9340,160.1139,...,33.08871,38.40972,44.24843,69.578600,4.019351,3.050024,3.039719,2.996142,2.967954,1.999594
2,2,30.426700,33.47752,44.809530,62.47495,77.43523,104.21530,102.7393,137.0004,186.0706,...,48.47132,74.71461,60.09090,7.073525,6.089851,6.537450,6.666096,7.306965,5.736840,3.625628
3,3,16.665490,30.10860,39.969520,44.12225,59.57512,77.56929,106.8925,166.5539,175.2381,...,60.55916,55.92124,15.17284,8.248324,36.680870,61.934130,20.268670,68.588190,46.498120,0.236010
4,4,8.815617,18.35160,8.658275,27.58590,48.62691,60.18013,91.3286,145.7109,116.0653,...,47.42691,69.20731,44.95468,29.171970,17.916740,16.255150,14.655590,17.260480,31.222450,46.717040